# Time series stuff

```{r}
date()
```

```{r}
# dplyr, tidyr packages and BPRSL are available
library(dplyr)
library(tidyr)
library(ggplot2)

rats = read.csv('data/rats.csv')
rats$ID = as.factor(rats$ID)
rats$Group = as.factor(rats$Group)
glimpse(rats)
```


```{r}
# dplyr, tidyr & ggplot2 packages and BPRSL are available
BPRSL = rats
# Standardise the variable bprs
BPRSL <- BPRSL %>%
  group_by(WD) %>%
  mutate(stdbprs = (rats - mean(rats)) / sd(rats)) %>%
  ungroup()

# Glimpse the data
glimpse(BPRSL)

#Access the package ggplot2
library(ggplot2)

# Draw the plot
ggplot(BPRSL, aes(x = WD, y = stdbprs, linetype = ID)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ Group, labeller = label_both) +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(min(BPRSL$stdbprs), max(BPRSL$stdbprs)))
```


Before standardization the time series seemed to have an upward trend but now they are in line. There are clear differences between groups though.


```{r}
# Number of weeks, baseline (week 0) included
n <- BPRSL$WD %>% unique() %>% length()

# Summary data with mean and standard error of bprs by treatment and week 
BPRSS <- BPRSL %>%
  group_by(Group, WD) %>%
  summarise( mean = mean(rats), se = sd(rats) / sqrt(n) ) %>%
  ungroup()

# Glimpse the data
glimpse(BPRSS)

# Plot the mean profiles
ggplot(BPRSS, aes(x = WD, y = mean, linetype = Group, shape = Group)) +
  geom_line() +
  scale_linetype_manual(values = c(1,2,3)) +
  geom_point(size=3) +
  scale_shape_manual(values = c(1,2,3)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se, linetype="1"), width=0.3) +
  theme(legend.position = c(0.8,0.8)) +
  scale_y_continuous(name = "mean(bprs) +/- se(bprs)")

```

```{r}
# dplyr, tidyr & ggplot2 packages and BPRSL are available

# Create a summary data by treatment and subject with mean as the summary variable (ignoring baseline week 0).
BPRSL8S <- BPRSL %>%
  filter(WD > 0) %>%
  group_by(Group, ID) %>%
  summarise( mean=mean(rats) ) %>%
  ungroup()

# Glimpse the data
glimpse(BPRSL8S)

# Draw a boxplot of the mean versus treatment
ggplot(BPRSL8S, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "mean(bprs), weeks 1-8")
```

We can exclude the outlier using a threshold of 550
```{r}
# Create a new data by filtering the outlier and adjust the ggplot code the draw the plot again with the new data
BPRSL8S1 <- BPRSL8S %>% filter(mean < 550)

# Draw a boxplot of the mean versus treatment
ggplot(BPRSL8S1, aes(x = Group, y = mean)) +
  geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape=23, size=4, fill = "white") +
  scale_y_continuous(name = "mean(bprs), weeks 1-8")


```
